regtests: test_watchtower started failing due to newly exposed bug
local_watchtower.adb.start_network was getting called twice.

follow-up b179b662a84ffd8606fb397d1a084bdc79526e0a

```
20230418T014725.636141Z |    ERROR | __main__ |
Traceback (most recent call last):
  File "/home/user/wspace/electrum/./run_electrum", line 435, in main
    handle_cmd(
  File "/home/user/wspace/electrum/./run_electrum", line 469, in handle_cmd
    d = daemon.Daemon(config, fd)
  File "/home/user/wspace/electrum/electrum/util.py", line 462, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/user/wspace/electrum/electrum/util.py", line 458, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/wspace/electrum/electrum/daemon.py", line 404, in __init__
    self.network = Network(config, daemon=self)
  File "/home/user/wspace/electrum/electrum/network.py", line 348, in __init__
    self.local_watchtower.adb.start_network(self)
  File "/home/user/wspace/electrum/electrum/address_synchronizer.py", line 185, in start_network
    assert self.network is None, "already started"
AssertionError: already started
```