qml: log and reraise any exceptions in the constructor of QEAbstractInvoiceListModel, so we at least see the root cause of the confusing AttributeError: 'QEWallet' object has no attribute 'requestModel'