follow-up prev
The Windows build was failing due to the trailing slash in the path:
```
💬 INFO:  Pip installing Electrum. This might take a long time if the project folder is large.
Processing c:\electrum
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [10 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\electrum\setup.py", line 75, in <module>
      find_packages('electrum/', exclude=["tests", "gui.kivy", "gui.kivy.*"])]),
    File "C:\python3\lib\site-packages\setuptools\discovery.py", line 103, in find
      convert_path(str(where)),
    File "C:\python3\lib\site-packages\setuptools\_distutils\util.py", line 130, in convert_path
      raise ValueError("path '%s' cannot end with '/'" % pathname)
  ValueError: path 'electrum/' cannot end with '/'
```
This is weird because I tested the setuptools.find_packages invocation on Linux, where it
has no issues with the trailing slash, but indeed it looks like on Windows it does.
Not sure why it behaves differently depending on the platform. Anyway, removing.