scripts: fix regression in quick_start.py
```
$ ./electrum/scripts/quick_start.py
Traceback (most recent call last):
  File "/home/user/wspace/electrum/./electrum/scripts/quick_start.py", line 32, in <module>
    wallet.start_network(network)
  File "/home/user/wspace/electrum/electrum/wallet.py", line 620, in start_network
    assert self.network is None, "already started"
AssertionError: already started
```
just the sanity check added in b179b662a84ffd8606fb397d1a084bdc79526e0a